services:
  disk-stats:
    build: .
    container_name: kometa-sidecar-disk-stats
    environment:
      - TZ=Australia/Sydney
      - KOMETA_TIME=55 23,5,11,17 * * *
      - DATA_PATH=/data
      - MOVIES_PATH=/data/media/movies
      - TV_PATH=/data/media/tv
    volumes:
      - /path/to/your/kometa/config:/config
      - /data:/data:ro
    restart: unless-stopped
